name: Screel Deployment
on: push
jobs:
  Lint: 
    runs-on: ubuntu-latest 
    steps:
      - name: Pull repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install 
      - name: run lint 
        run: npm run lint 
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Pull repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install 
      - name: Feedback
        run: echo "Testing project"
      - name: run test 
        run: npm run test 
  Build:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: Pull repo
        uses: actions/checkout@v3
      - name: cache dependencies
        uses: actions/cache@v3
        with: 
          path: ~/.npm
          key: depencency-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm install 
      - name: Feedback
        run: echo "Deploying project"
      - name: run build 
        run: npm run build 
